name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.15', '1.17']
    defaults:
      run:
        working-directory: ./frameworks/go
    steps:
        - name: Test and Run
        - run: actions/checkout@v2
        - run: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}
        - run: go test soma_test.go
        - run: go run main.go

        - name: Set up QEMU
          run: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          run: docker/setup-buildx-action@v2

        - name: Build and Push
          id: docker_build
          run: docker/build-push-action@v2
          with:
            push: false
            tags: tiagonerv1987/golang-app:${{ matrix.go }}
            context: ./frameworks/go
            dockerfile: Dockerfile